#!/usr/bin/python

import sys
from pathlib import Path
from parser import Parser

if __name__ == '__main__':
    if not len(sys.argv) == 3:
        print("Usage: pyuxncle [source] [out]")

    inFile = sys.argv[1]
    outFile = sys.argv[2]
    src = Path(inFile).read_text()
    parse = Parser(src, outFile)
    parse.parse()