#!/usr/bin/python

from parser import Parser

testSrc = """
int total = 0;
int x = 10;

while (x >= 1) {
    total = total + x;
    x = x - 1;
}

print total;
"""

parse = Parser(testSrc)
parse.parse()